language: node_js
node_js: "6"

install: npm install

script:
    - yarn build
    npm run generate

deploy:
  provider: pages
  cleanup: true
  strategy: git
  github_token: $git_hub_token
  on:
    branch: master
  local_dir: $TRAVIS_BUILD_DIR/docs
  target-branch: gh-pages
  verbose: true
