language: node_js
node_js: "6"

install: npm install

script:
    npm run generate

deploy:
  provider: pages
  cleanup: true
  strategy: git
  token: $git_hub_token
  local_dir: docs
  on:
    branch: master
    target_branch: gh-pages
    verbose: true
