language: node_js
node_js: "6"

install: npm install

script:
    # Create the docs directory. This is where we will be publishing from
    # (see the "deploy" section below).
    - mkdir -p docs/
    # Use reveal-md to generate static docs.
    - reveal-md slides.md --static docs --disable-auto-open --theme white
    - cp -r assets docs/.
    # Use reveal-md to generate PDF.
    - reveal-md slides.md --disable-auto-open --theme white --print slides.pdf
    - cp slides.pdf docs/.
    - yarn build
    npm run generate

deploy:
  provider: pages
  cleanup: true
  strategy: git
  github_token: $git_hub_token
  on:
    branch: master
  local_dir: docs
  target-branch: gh-pages
  verbose: true
