language: node_js
node_js: "6"

install: npm install

script: npm run generate

deploy:
  provider: pages
  cleanup: true
  local_dir: docs
  strategy: git
  github_token: $GITHUB_TOKEN
  on:
    branch: master
